apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-stream
  labels:
    name: twitter-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      name: twitter-stream
  template:
    metadata:
      labels:
        name: twitter-stream
    spec:
      containers:
      - name: twitter-to-pubsub
        image: gcr.io/google-samples/pubsub-bq-pipe:v5
        env:
        - name: PROCESSINGSCRIPT
          value: twitter-to-pubsub
        # This is the name of pubsub topic
        - name: data-inside
          value: projects/your-project/topics/your-topic
        # The following four settings are the twitter credentials information.
        - name: CONSUMERKEY
          value: eDD86PgwAgxbILliCTpShddAw
        - name: CONSUMERSECRET
          value: h2QmnqJzpdAnflxkEM0ugWbXmOGXacNvmfuzsLndkBwHuXGAi9
        - name: ACCESSTOKEN
          value: 836261139352813569-UhjRlrZmylxrFF5X2uzL0GLIAi1yVxI
        - name: ACCESSTOKENSEC
          value: 4eGLrLI6SAnePUjRJsmk11Vempp6G01pOWVG8Y7PHdnir
        - name: TWSTREAMMODE
          value: sample
